### PR TITLE
Column unquote

### PR DESCRIPTION
**Pull request by Arthasasyan**

### CODE REVIEW

**Comment by alexandertokarev** [comment]
1) Tag value itself should be quoted:
 
```
 statement.cpp:144 prepareQuery scan_escape_sequences: 1 query: select "a"."tags.test-test" from cpu_busy prepared_query: select "a".tags.test-test from cpu_busy 
```
"a".tags.test-test  is invalid, should be "a".tags."test-test"



2)  Some query tool may generate a query without table name, for example `select "tags.test" `

```
statement.cpp:144 prepareQuery scan_escape_sequences: 1 query: select "tags.test" from cpu_busy prepared_query: select "tags.test" from cpu_busy 
```

3) Ensure the value is not a part of a string constant: ` concat(' "a"."b.c" ', entity)`
```
statement.cpp:144 prepareQuery scan_escape_sequences: 1 query: select concat(' "a"."b.c" ', entity) from cpu_busy limit 1 prepared_query: select concat ( ' "a".b.c ' , entity ) from cpu_busy limit 1 
```

4) Escaped quotes processed incorrectly:

```
 statement.cpp:144 prepareQuery scan_escape_sequences: 1 query: select "a"."tags.c""d" from cpu_busy limit 1 prepared_query: select "a".tags.c "d"  from cpu_busy limit 1 
```

**Comment by Arthasasyan** [comment]
1. Probably, we can replace with another rule: `"a"."tags.test"` -> `"a"."tags"."test"
4.  Could you, please, explain, what's wrong with this query? It works in SQL console if declaring allies for table

**Comment by alexandertokarev** [comment]
> 1. Probably, we can replace with another rule: `"a"."tags.test"` -> `"a"."tags"."test"`

Yes, this should work properly.

> 2. Could you, please, explain, what's wrong with this query? It works in SQL console if declaring allies for table

The query below does not work:

```sql
select "tags.test" from cpu_busy limit 1
IllegalArgumentException: Unexpected expression: 'tags.test'
```

I think we should unquote all columns that start with **tags.** even though there is no table alias specified.

**Comment by Arthasasyan** [comment]
Sorry for misunderstanding, markdown autocratically changed numeration in my comment. I was asking about 4th point

**Comment by alexandertokarev** [comment]
The parser translates this query:

```sql
select "a"."tags.c""d" from cpu_busy a limit 1
```
to

```sql
select "a".tags.c "d"  from cpu_busy a limit 1 
```

The correct query is :

```sql
select "a".tags."c""d"  from cpu_busy a limit 1 
```

**Comment by Arthasasyan** [comment]
At the moment it works with all 4 cases
@alexandertokarev Should we add a rule to ignore table names and allies? If the table is named, for example, `entity.main`

**Comment by alexandertokarev** [comment]
> At the moment it works with all 4 cases
> @alexandertokarev Should we add a rule to ignore table names and allies? If the table is named, for example, `entity.main`

Yes, please try to detect if this is a table name or alias. 
If a string is in **from** or **join** clause or followed by a dot.

**Comment by Arthasasyan** [comment]
TODO: write a finite state machine for searching colons

**Comment by Arthasasyan** [comment]
Opened #9 to configure state machine

**Pull request merged**
