### PR TITLE
Created column state machine

### PR DESCRIPTION
**Pull request by Arthasasyan**
Changed unqoute logic to state machine. At the moment VS 2017 cannot compile it, probably due to classes are referencing each other

### CODE REVIEW

**Comment by Arthasasyan** [comment]
Current error log:

```cpp
"C:\atsd-odbc\vs\odbc64.sln" (default target) (1) ->
       "C:\atsd-odbc\vs\driver64\driver64.vcxproj" (default target) (2) ->
         c:\atsd-odbc\driver\escaping\state_machine.h(12): error C2440: 'initializing': cannot convert from 'initializer list' to 'std::list<Token,std::allocator<_Ty>>' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(34): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(41): error C3646: 'stateMachine': unknown override specifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(41): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(34): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(34): error C2614: 'BaseState': illegal member initialization: 'stateMachine' is not a base or member [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(46): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(46): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(56): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(56): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(60): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(60): error C3861: 'ColumnState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(63): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(63): error C3861: 'FunctionOrClauseState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(70): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(70): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(74): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(74): error C3861: 'TableState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(77): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(81): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(84): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(85): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(85): error C3861: 'AlliesState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(88): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(92): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(92): error C3861: 'FunctionOrClauseState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(115): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(115): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(116): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(117): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(123): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(125): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(126): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(129): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(129): error C3861: 'TableState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(132): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(135): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(135): error C3861: 'FunctionOrClauseState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(142): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(142): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(146): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(148): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(149): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(152): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(152): error C3861: 'TableState': identifier not found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(155): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(158): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(165): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(165): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(169): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(172): error C2065: 'stateMachine': undeclared identifier [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         c:\atsd-odbc\driver\escaping\state_machine.h(187): error C2661: 'SelectState::SelectState': no overloaded function takes 2 arguments [C:\atsd-odbc\vs\driver64\driver64.vcxproj]

    0 Warning(s)
    104 Error(s)
```

**Comment by alexandertokarev** [comment]
`c:\atsd-odbc\driver\escaping\state_machine.h(12): error C2440: 'initializing': cannot convert from 'initializer list' to 'std::list<Token,std::allocator<_Ty>>' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
`

This should be 

```cpp
const std::list<Token::Type> function_list{
```

on line 12

**Comment by alexandertokarev** [comment]
`c:\atsd-odbc\driver\escaping\state_machine.h(34): error C2061: syntax error: identifier 'StateMachine' [C:\atsd-odbc\vs\driver64\driver64.vcxproj]`

Use [forward declaration
](https://en.cppreference.com/w/cpp/language/class#Forward_declaration)

**Comment by alexandertokarev** [comment]
If you pass parameters by reference to a class constructor then class members should also be references:

```cpp
    protected:
        const Token& token;
        StateMachine& stateMachine;
```

**Comment by alexandertokarev** [comment]
```cpp
        BaseState& nextState(const Token& nextToken) {
            const std::string literal = nextToken.literal.to_string();
            if(matchesColumnRegex(literal)) {
                return (BaseState&) ColumnState(nextToken, stateMachine);
            } else {
                return (BaseState&) FunctionOrClauseState(nextToken, stateMachine); 
            }
        };
```

The new objects (ColumnState and FunctionOrClauseState ) are created on the stack as  local variables and will be removed after exiting the **nextState** function.  Consider creating new objects using operator **new** and delete these objects in the destructor using operator **delete**

**Comment by alexandertokarev** [comment]
> Consider creating new objects using operator new and delete these objects in the destructor using operator delete

Another possible solution: store the current token in the StateMachine object and make state classes singletons so that you do not need to create new objects when changing state.

**Comment by Arthasasyan** [comment]
@alexandertokarev could you help me with solving linking problems?

```cpp

Build FAILED.

       "C:\atsd-odbc\vs\odbc64.sln" (default target) (1) ->
       "C:\atsd-odbc\vs\driver64w\driver64w.vcxproj" (default target) (6) ->
       (Link target) -> 
         atsdodbcw.exp : warning LNK4070: /OUT:atsdodbc.dll directive in .EXP differs from output filename 'C:\atsd-odbc\vs\x64\Release\atsdodbcw.dll'; ignoring directive [C:\atsd-odbc\vs\driver64w\driver64w.vcxproj]


       "C:\atsd-odbc\vs\odbc64.sln" (default target) (1) ->
       "C:\atsd-odbc\vs\driver64w\driver64w.vcxproj" (default target) (6) ->
       (Link target) -> 
         escape_sequences.obj : error LNK2001: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl StateMachine::run(void)" (?run@StateMachine@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [C:\atsd-odbc\vs\driver64w\driver64w.vcxproj]
         C:\atsd-odbc\vs\x64\Release\atsdodbcw.dll : fatal error LNK1120: 1 unresolved externals [C:\atsd-odbc\vs\driver64w\driver64w.vcxproj]


       "C:\atsd-odbc\vs\odbc64.sln" (default target) (1) ->
       "C:\atsd-odbc\vs\driver64\driver64.vcxproj" (default target) (2) ->
         escape_sequences.obj : error LNK2005: "bool __cdecl matchesColumnRegex(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?matchesColumnRegex@@YA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in escape_sequences.obj [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         escape_sequences.obj : error LNK2005: "bool __cdecl inTableKeywordsList(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?inTableKeywordsList@@YA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in escape_sequences.obj [C:\atsd-odbc\vs\driver64\driver64.vcxproj]
         C:\atsd-odbc\vs\x64\Release\atsdodbc.dll : fatal error LNK1169: one or more multiply defined symbols found [C:\atsd-odbc\vs\driver64\driver64.vcxproj]

    1 Warning(s)
    5 Error(s)
```

**Comment by alexandertokarev** [comment]
Now build_vs.bat  completed successfully

**Comment by Arthasasyan** [comment]
It seems that `IntermediateState.nextState` returns broken pointer. I'll try to modify logic so that we don't need `IntermediateState`

**Comment by Arthasasyan** [comment]
```sql
SELECT "bi.ex_017.m"."datetime" AS "datetime",
"bi.ex_017.m"."entity" AS "entity",
"bi.ex_017.m"."entity.groups" AS "entity_groups",
"bi.ex_017.m"."entity.tags" AS "entity_tags",
"bi.ex_017.m"."metric" AS "metric",
"bi.ex_017.m"."metric.tags" AS "metric_tags",
"bi.ex_017.m"."text" AS "text",
"bi.ex_017.m"."time" AS "time",
"bi.ex_017.m"."value" AS "value"
FROM "bi.ex_017.m"
```

Converted to:
```sql
SELECT "bi.ex_017.m"."datetime" AS "datetime" , "bi.ex_017.m"."entity" AS "entity" , "bi.ex_017.m"."entity"."groups" AS "entity_groups" , "bi.ex_017.m"."entity"."tags" AS "entity_tags" , "bi.ex_017.m"."metric" AS "metric" , "bi.ex_017.m"."metric"."tags" AS "metric_tags" , "bi.ex_017.m"."text" AS "text" , "bi.ex_017.m"."time" AS "time" , "bi.ex_017.m"."value" AS "value" FROM "bi.ex_017.m" 
```

**Comment by Arthasasyan** [comment]
We probably also need to modify `ColumnState.nextState` for case with allies state. Now it will only work if allies matches column regex.
I suppose that the only way is to declare all functions and keywords and check for `FunctionOrClauseState` first. But it's too not optimized way.
@alexandertokarev what do you think? Should we ever do something with it? Probably, it's not a problem if allies that does not match regex messes with function state?

**Comment by Arthasasyan** [comment]
@alexandertokarev please, take a look at this
Please, note that this PR will be merged not to master, but to branch from #8

**Comment by alexandertokarev** [comment]
> We probably also need to modify `ColumnState.nextState` for case with allies state. Now it will only work if allies matches column regex.
> I suppose that the only way is to declare all functions and keywords and check for `FunctionOrClauseState` first. But it's too not optimized way.
> @alexandertokarev what do you think? Should we ever do something with it? Probably, it's not a problem if allies that does not match regex messes with function state?

Could you please provide an example query that may cause this problem?

**Comment by Arthasasyan** [comment]
I suppose that even if this case can be triggered, it's not a problem for column unquoting as `AlliesState` and `FunctionOrClauseState` are almost identical

**Comment by Arthasasyan** [comment]
Some changes have to be made to prevent this transformation:

```sql
query: SELECT "ENTITY.label" FROM "cpu_busy" AS "metric.1" prepared_query: SELECT "ENTITY"."label" FROM "cpu_busy" AS "metric"."1"
```

**Comment by Arthasasyan** [comment]
I had to remove link to a token, because I need it's value to be constant, not a link to a value

**Comment by Arthasasyan** [comment]
Previously query with `FROM "table" JOIN "table_2" "metric.2"` was translated to `FROM "table" JOIN "table_2" "metric"."2"` because on `LOIN` keyword state became `FunctionOrClauseState`
Now the follow query is not changed(except extra spaces):

```sql
SELECT t1.entity, t1.datetime, t1.value, "metric.1".value
FROM "mpstat.cpu_busy" t1
JOIN "mpstat.cpu_idle" "metric.1"
WHERE t1.datetime > NOW - 1 * HOUR
AND t1.entity = 'nurswgvml006'
```

**Comment by Arthasasyan** [comment]
Problem with subquery: missing `GROUP`
```sql
query: SELECT datetime, AVG(value) AS "daily_average"
FROM
(
SELECT datetime, MAX(value) AS "value"
FROM "mpstat.cpu_busy" WHERE datetime >= CURRENT_WEEK
GROUP BY PERIOD(1 HOUR)
)
GROUP BY PERIOD(1 DAY) 
prepared_query: SELECT datetime , AVG ( value ) AS "daily_average" 
FROM ( SELECT datetime , MAX ( value ) AS "value" 
FROM "mpstat.cpu_busy" WHERE datetime >= CURRENT_WEEK GROUP BY PERIOD ( 1 HOUR ) ) 
BY PERIOD ( 1 DAY ) 
```

Probably because of bad cycle, trying to fix

**Comment by Arthasasyan** [comment]
Closed accidently

**Comment by Arthasasyan** [comment]
Fixed
```sql
query: SELECT datetime, AVG(value) AS "daily_average"
FROM
(
SELECT datetime, MAX(value) AS "value"
FROM "mpstat.cpu_busy" WHERE datetime >= CURRENT_WEEK
GROUP BY PERIOD(1 HOUR)
)
GROUP BY PERIOD(1 DAY) 
prepared_query: 
SELECT datetime , AVG ( value ) AS "daily_average"
 FROM ( SELECT datetime , MAX ( value ) AS "value" 
FROM "mpstat.cpu_busy" WHERE datetime >= CURRENT_WEEK GROUP BY PERIOD ( 1 HOUR ) )
GROUP BY PERIOD ( 1 DAY ) 
```

**Comment by Arthasasyan** [comment]
At the moment we do not support comments, because `--` is translated to `- -`
I'm not sure if we should do anything with it, because query is translated to one file anyway

**Comment by Arthasasyan** [comment]
I suppose, this can be fixed with lexer update, because now it ignores spaces and new line symbols

**Comment by Arthasasyan** [comment]
Update: it does not ignore these symbols, but translate it to `Token::SPACE` if `emit_space` is `true` https://github.com/axibase/atsd-odbc/blob/16c30117782d3c854c3fde333cc8cdcf87cc97c1/driver/escaping/lexer.cpp#L132

**Comment by Arthasasyan** [comment]
Fixed without `Lexer` class changes

**Comment by Arthasasyan** [comment]
State machine logic is done now, @alexandertokarev please take a look at it

**Comment by Arthasasyan** [comment]
```log
3426010728 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:36 --- State created: 1
3426010783 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:36 --- State created: 2
3426010796 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:45 --- State deleted: 1
3426010814 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:36 --- State created: 3
3426010825 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:45 --- State deleted: 2
3426010860 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:36 --- State created: 4
3426010871 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:45 --- State deleted: 3
3426010888 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:36 --- State created: 5
3426010898 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:45 --- State deleted: 4
3426010909 [2964] c:\atsd-odbc\driver\escaping\state_machine.h:45 --- State deleted: 5
```

**Pull request merged**
